"""ganti pw ke 250

Revision ID: 242d39b4db5e
Revises: 07ae70b18224
Create Date: 2025-12-11 14:46:47.480158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '242d39b4db5e'
down_revision = '07ae70b18224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descreption')
        batch_op.drop_column('todos')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todos', mysql.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('descreption', mysql.TEXT(), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('todo')

    # ### end Alembic commands ###
