"""alter tabel todos

Revision ID: 67426c7734ba
Revises: 242d39b4db5e
Create Date: 2025-12-19 00:02:40.609446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67426c7734ba'
down_revision = '242d39b4db5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_access', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_refresh', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('token_refresh')
        batch_op.drop_column('token_access')

    # ### end Alembic commands ###
